import pandas as pd


df = pd.read_csv('coffeeparser/data/coffee.csv')
print(df)

'''
Получаем слудующий вывод 

0             Подарочный набор с кофе Rise для Богинь  https://specialty.ru/coffee/podarochnyy-nabor-...
1   Кофе Бразилия Серрадо Минейро Пиберри от Balti...  https://specialty.ru/coffee/kofe-braziliya-ser...
2           Кофе Кения Меру от Baltic Coffee Roasters      https://specialty.ru/coffee/kofe-keniya-meru/
3       Кофе Мексика Чьяпас от Baltic Coffee Roasters  https://specialty.ru/coffee/kofe-meksika-chyapas/
4   Кофе Бразилия Фазенда Топазо от Baltic Coffee ...  https://specialty.ru/coffee/kofe-braziliya-faz...
5    Кофе Кения Мара Эстейт от Baltic Coffee Roasters  https://specialty.ru/coffee/kofe-keniya-mara-e...
6   Кофе Индонезия Фринса Эстейт от Baltic Coffee ...  https://specialty.ru/coffee/kofe-indoneziya-fr...
7           Кофе Бразилия Пиберри от Мануфактура кофе  https://specialty.ru/coffee/kofe-braziliya-pib...
8                              Дрип-пакеты Кения Меру  https://specialty.ru/coffee/drip-pakety-keniya...
9   Кофе Бразилия Суль-де-Минас Сантос от Мануфакт...  https://specialty.ru/coffee/kofe-braziliya-sul...
10         Кофе Эфиопия Иргачеффе от Мануфактура кофе  https://specialty.ru/coffee/kofe-efiopiya-irga...
11          Кофе Колумбия Супремо от Мануфактура кофе  https://specialty.ru/coffee/kofe-kolumbiya-sup...
12    Кофе Мексика Чьяпас Муксбал от Мануфактура кофе  https://specialty.ru/coffee/kofe-meksika-chyap...
13            Кофе Эфиопия Кочере от Мануфактура кофе  https://specialty.ru/coffee/kofe-efiopiya-koch...
14                Кофе Кения Мара от Мануфактура кофе      https://specialty.ru/coffee/kofe-keniya-mara/
15           Кофе Бразилия Топазо от Мануфактура кофе  https://specialty.ru/coffee/kofe-braziliya-top...
16   Кофе Индонезия Фринса Эстейт от Мануфактура кофе  https://specialty.ru/coffee/kofe-indoneziya-fr...
17                           Дрип-бокс БРЮБЕРРИМОР 15  https://specialty.ru/coffee/drip-boks-bryuberr...
18                Кофе Бразилия Декаф от Хороший Тигр  https://specialty.ru/coffee/kofe-braziliya-dek...
19                    Кофе Перу Эхарт от Хороший Тигр      https://specialty.ru/coffee/kofe-peru-ekhart/
20                  Кофе Эфиопия Лиму от Хороший Тигр  https://specialty.ru/coffee/kofe-efiopiya-limu_1/
21        Кофе Руанда Южная Провинция от Хороший Тигр  https://specialty.ru/coffee/kofe-ruanda-yuzhna...
22       Кофе Колумбия Розовый Бурбон от Хороший Тигр  https://specialty.ru/coffee/kofe-kolumbiya-roz...
23                              Эспрессо от Specialty  https://specialty.ru/coffee/espresso-ot-specia...
24  Кофе Бразилия Суль-де-Минас Conquista Capoeiri...  https://specialty.ru/coffee/kofe_brazil_sul_du...
25    Кофе Вьетнам Тхай нгуен от Neva Coffee Roasters  https://specialty.ru/coffee/kofe_vietnam_thai_...
26  Кофе Бразилия Серрадо Минейро Кооператив Коком...  https://specialty.ru/coffee/kofe_brazil_cerrad...
27  Кофе Колумбия Уила Супремо от Neva Coffee Roas...  https://specialty.ru/coffee/kofe_colombia_huil...
28                    Капсулы Nespresso Эфиопия Гедеб  https://specialty.ru/coffee/kapsuly_ethiopia_g...
29                Кофе Бразилия Суль-де-Минас SHB от   https://specialty.ru/coffee/kofe-braziliya-sul...
30         Капсулы Nespresso Бразилия Серрадо Минейро  https://specialty.ru/coffee/kapsuly_brazil_cer...
31      Кофе Колумбия Антьокия Супремо от Just Coffee  https://specialty.ru/coffee/kofe_colombia_anti...
32              Кофе Бразилия Моджиана от Just Coffee  https://specialty.ru/coffee/kofe_brazil_mogian...
33  Кофе Бразилия Суль-де-Минас GTFC от BolsheCoff...  https://specialty.ru/coffee/kofe_brazil_sul_du...
34  Кофе Гондурас Комаягуа Ла Эсмеральда от Bolshe...  https://specialty.ru/coffee/kofe-gonduras-koma...


'''